services:
  - type: web
    name: mood-detective-backend
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
